name = "spinogambinocasino-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino.com.pt"
HMAC_KEY = "a207c384a6720ecc4adfd9f256bce0491a532d6ed3351c2605fc06572973d140"
COOKIE_NAME = "g5n"
PLAY_PATH = "visit"
BUTTON_ID = "p04dbff3d438f83bf583cf2f3cfec1fa8"
GATE_SALT = "9ad4514364835eb3"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ureh"
CTA_SELECTOR = ".play-button"
